# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  advent2017-benchmarks:
    dependencies:
    - base
    - advent2017
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: advent2017 is a new Haskeleton package.
executables:
  advent2017:
    dependencies:
    - base
    - advent2017
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/advent2017
library:
  dependencies:
  - base
  - text
  - flow
  source-dirs: library
default-extensions:
  - OverloadedStrings
  - ScopedTypeVariables
license: MIT
maintainer: Author name here
name: advent2017
synopsis: A new Haskeleton package.
tests:
  advent2017-test-suite:
    dependencies:
    - base
    - advent2017
    - hspec
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
